require: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Metrics/AbcSize:
  Max: 26

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 200

Naming/FileName:
  Exclude:
    - "lib/vagrant-tart.rb"

RSpec/ExampleLength:
  Max: 15

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 7

RSpec/VerifiedDoubleReference:
  EnforcedStyle: string

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
