title: Vagrant Tart
email: laurent.etiemble@gmail.com
description: >-
  Vagrant-tart is a Vagrant plugin that adds a Tart provider to Vagrant, allowing Vagrant
  to control and provision machines via Tart command line tool.
baseurl: "/vagrant-tart"
url: "https://letiemble.github.io"
twitter_username: letiemble
github_username:  letiemble
repository: letiemble/vagrant-tart

# Build settings
remote_theme: just-the-docs/just-the-docs@v0.8.2
plugins:
  - jekyll-remote-theme
