name: Execute Rake tasks

on:
  # Runs when a new commit is pushed on a branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read

jobs:
  test:
    runs-on: macos-latest

    strategy:
      matrix:
        ruby-version:
          - '3.1'
          - '3.2'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby-version }}
    - name: Run tests
      run: bundle exec rake
